In [2]:
#if-else

import numpy as np

randNum = np.random.randn()
if randNum > 0:
    print("Positive")

Positive


In [3]:
cakeType = "None"

if cakeType == "Chocolate":
    print("Chocolate cake")
elif cakeType == "Vanilla":
    print("Vanilla cake")
else:
    print("No cake, you're healthy")

No cake, you're healthy


In [9]:
#one line if statements
caketype1 = "Chocolate"
print("Chocolate cake") if caketype1[0] == "C" else print("No cake, you're healthy")

Chocolate cake


In [10]:
#conjunctive conditional
cakeType2 = "Chocolate"
cakeType3 = "Vanilla"
if cakeType2 == "Chocolate" and cakeType3 == "Vanilla":
    print("Chocolate and Vanilla cake")
else:
    print("No cake, you're healthy")

Chocolate and Vanilla cake


In [12]:
#Exercise 
#create a dot product function
#function checks if both inputs are numpy arrays
#function checks for same length of input arrays
#function returns dot product of input arrays

def dotProduct(x,y):
    if type(x) == np.ndarray and type(y) == np.ndarray:
        if len(x) == len(y):
            return sum(x*y)
        else:
            print("Arrays are not the same length")
    else:
        print("One or both inputs are not numpy arrays")

x = np.array([1,2,3])
y = np.array([4,5,6])
print(dotProduct(x,y))
print(np.dot(x,y))

32
32


In [13]:
#for loop
for i in range(5):
    print(i)


0
1
2
3
4


In [15]:
import numpy as np

numbers = np.linspace(3,17,14)

for i in numbers:
    print(i)

3.0
4.076923076923077
5.153846153846153
6.230769230769231
7.3076923076923075
8.384615384615383
9.461538461538462
10.538461538461538
11.615384615384615
12.692307692307692
13.769230769230768
14.846153846153845
15.923076923076923
17.0


In [16]:
#softcoding vs hardcoding
#softcoding is using variables instead of hardcoding values
#hardcoding is using values directly in code

for i in range(100):
    pass 

#vs

aVar = 100
for i in range(aVar):
    pass

#avoid hardcoding values



In [19]:
import sklearn as sk

In [20]:
import tensorflow as tf

In [21]:
#Exercise
#create a function that reports the fibonacci sequence for n+3 numbers

def fib(n):
    a = 0
    b = 1
    for i in range(n+3):
        print(a)
        a,b = b,a+b

fib(10)

0
1
1
2
3
5
8
13
21
34
55
89
144


In [22]:
#continue

for i in range(10):
    if i%2 == 0:
        continue
    print(i)

1
3
5
7
9


In [23]:
#while loops

counter = 10
while counter > 0:
    print(counter)
    counter -= 1

10
9
8
7
6
5
4
3
2
1


In [25]:
#Exercise
#Make a poisson-like counter
#parameter lambda, positive number. ex- 10
#start another number at 1 and multiply it by a random number drawn from a uniform distribution between 0 and 1
#until target number is smaller than exp(-lambda)
#create a counter that counts how many times the random number is multiplied by the uniform distribution

import numpy as np

def poisson(lamb):
    target = np.exp(-lamb)
    number = 1
    counter = 0
    while number > target:
        number *= np.random.uniform(0,1)
        counter += 1
    return counter

print(poisson(10))

9


In [26]:
#initialization
import numpy as np
r = np.zeros(10)

for i in range(10):
    r[i] = i**2
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [27]:
r = [0 for _ in range(10)]

In [28]:
print(r)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [29]:
r = np.full(10,0)

In [30]:
r

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
r = np.array([])

for i in range(10):
    r = np.append(r,i**2)

r

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [32]:
r = np.zeros((4,5))
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
#Exercise
#Time all three methods of initialization

import time

start = time.time()
r = np.zeros(100000000)
end = time.time()

print(end-start)

start = time.time()
r = [0 for _ in range(100000000)]
end = time.time()

print(end-start)



0.003290891647338867
1.4604969024658203


In [40]:
#Create a function that will input two numbers and return their product

def product(x,y):
    try:
        if x > 0 and y > 0:

            return x*y
    except:
        print("One or both inputs are not numbers")
product(5,"hi")

One or both inputs are not numbers


In [41]:
def product(x,y):
    if not isinstance(x,int) or not isinstance(y,int):
        raise Exception("One or both inputs are not numbers")
    else:
        return x*y
    
product(5,"hi")



Exception: One or both inputs are not numbers

In [42]:
#zip
#zip takes two lists and combines them into a list of tuples

someList = [1,2,3,4,5]
someOtherList = ["a","b","c","d","e"]
for i in range(len(someList)):
    print(someList[i],someOtherList[i])


1 a
2 b
3 c
4 d
5 e


In [43]:
for j,k in zip(someList,someOtherList):
    print(j,k)

1 a
2 b
3 c
4 d
5 e


In [45]:
#Exercise
#Create a function that takes two lists and returns a dictionary using zip

names = ["John","Mary","Joe","Sally"]
ages = [23,45,12,67]
aDict = {}
for i,j in zip(names,ages):
    aDict[i] = j
print(aDict)

{'John': 23, 'Mary': 45, 'Joe': 12, 'Sally': 67}
