In [1]:
import numpy as np

In [3]:
aList = [1, 2, 3, 4, 5]

In [4]:
a = np.array(aList)

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
np.mean(a)

3.0

In [8]:
np.linspace(0, 10, 20) #20 numbers linearly spaced between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
number = [1,2,3,4,5,6]
type(number)

list

In [10]:
numbernp = np.array(number)
type(numbernp)

numpy.ndarray

In [11]:
numbernp

array([1, 2, 3, 4, 5, 6])

In [12]:
numbernp.min()

1

In [14]:
numbernp.shape

(6,)

In [15]:
n = [4,6,7,2,1,9,8]
n.sort()

In [16]:
n

[1, 2, 4, 6, 7, 8, 9]